User --> Docker.Svelte: TCP/5173

Docker{
  Postgres {
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
  }
  
  Svelte {
    icon: https://avatars.githubusercontent.com/u/23617963?s=100&v=4
  }

  MedusaJS {
    API
    AdminConsole
  }

  MinIO {
    AdminConsole
    API
  }
}

User --> Docker.MedusaJS.AdminConsole: TCP/7001
User --> Docker.MinIO.AdminConsole: TCP/9090

Docker.Svelte --> Docker.MedusaJS.API: TCP/9000
Docker.MedusaJS.API --> Docker.Postgres: TCP/5432
Docker.MedusaJS.AdminConsole --> Docker.Postgres: TCP/5432
Docker.MedusaJS.AdminConsole --> Docker.MedusaJS.API
Docker.MedusaJS.AdminConsole --> Docker.MinIO.AdminConsole: TCP/9090
Docker.MinIO.AdminConsole -->  Docker.MinIO.API: TCP/9001
