services:
  backend:
    build:
      dockerfile: Backend.Dockerfile
    image: backend:test
    container_name: medusa-server
    ports:
      - 9000:9000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  admin:
    build:
      dockerfile: Admin.Dockerfile
    image: admin:test
    ports:
      - 7001:7001
    depends_on:
      - backend
    container_name: medusa-admin
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
