services:
  backend:
    build:
      dockerfile: Backend.Dockerfile
    image: backend:test
    container_name: backend
    ports:
      - 9000:9000
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: production
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
      MEDUSA_FF_TAX_INCLUSIVE_PRICING: true

  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  admin:
    build:
      dockerfile: Admin.Dockerfile
    image: admin:test
    container_name: medusa-admin
    ports:
      - 7001:9000
    depends_on:
      - backend
      - postgres
      - redis
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      REDIS_URL: redis://cache
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      GCS_CLIENT_EMAIL: cs-gcs-demo-rw@medusa-dev-de3a.iam.gserviceaccount.com
      GCS_PRIVATE_KEY: add-here
      GCS_PUBLIC_BUCKET_NAME: cs-medusa-images-demo
      GCS_BASE_PUBLIC_URL: https://storage.googleapis.com/cs-medusa-images-demo/

