# Use Node.js 20 as a parent image
FROM node:20 AS builder

# Set the working directory
WORKDIR /app

# Add build argument for repository URL
ARG MEDUSA_REPO

# Clone the repository (shallow clone)
RUN git clone --depth 1 $MEDUSA_REPO .

# Copy the local medusa-config.ts file to override the existing one
COPY medusa-config.ts /app/medusa-config.ts

COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

# Install dependencies
RUN yarn install

# Build the application
RUN yarn build

# SECOND STAGE: Minimal image for running the application
FROM node:20-slim

# Set the working directory
WORKDIR /app

# Copy necessary files from the builder stage
COPY --from=builder /app .

# Expose the application port
EXPOSE 9000

ENTRYPOINT [ "/app/entrypoint.sh" ]